- job:
    # TODO(kgiusti) this old test can be removed once ocata is no
    # longer supported At that point we only need the -hybrid and
    # -dual test cases
    name: devstack-plugin-amqp1-tempest-dsvm-full
    parent: legacy-dsvm-base
    run: playbooks/devstack-plugin-amqp1-tempest-dsvm-full/run.yaml
    post-run: playbooks/devstack-plugin-amqp1-tempest-dsvm-full/post.yaml
    timeout: 10800
    required-projects:
      - openstack/devstack-gate
      - openstack/devstack-plugin-amqp1
      - openstack/tempest

- project:
    check:
      jobs:
        - devstack-plugin-amqp1-tempest-dsvm-full:
            voting: false
        - oslo.messaging-src-dsvm-full-amqp1-hybrid:
            voting: false
            branches: ^(?!stable/ocata).*$
        - openstack-tox-bashate
    gate:
      jobs:
        - openstack-tox-bashate
