- project:
    check:
      jobs:
        - openstack-tox-bashate
        - oslo.messaging-src-dsvm-full-amqp1-hybrid
    gate:
      jobs:
        - openstack-tox-bashate
        - oslo.messaging-src-dsvm-full-amqp1-hybrid
